### ISSUE TITLE
Incorrect formating when code block contain a pipe

### ISSUE THREAD

**Issue by AxFrancois** [TomasHubelbauer/vscode-markdown-table-format#7]
Hello ! 

I've been using this extension quite a lot; it's very useful, but I encountered a bug with it today. I needed to add an nmap log to a markdown file, but upon using the linter, it instantly destroyed it despite it being placed in a fenced code block. Here is a sample string:
```
    ```
    21/tcp   open   ftp         vsftpd 2.3.4
    | vulners
    |
    [...]
    ```
```

And when I use the linter, it becomes : 
```
    ```
    21/tcp   open   ftp         vsftpd 2.3.4
    |
    |
    |
    [...]
    ```
```
I believe it should not be considered a table because somehow it does.
I would have loved to help code a fix, but unfortunately, I'm allergic to JavaScript and TypeScript.

Thanks again

**Comment by TomasHubelbauer** [comment]
Hey, unfortunately I don't use this extension myself anymore since Prettier can now format Markdown documents and tables. Even if you're not working on a web dev project, it might be worth installing Prettier for this functionality for you - I checked your code block and it doesn't suffer the same problem as my extension. I might get around to fixing this at some point, but right now my VS Code extension aren't my focus and honestly for basic stuff like MarkDown table formatting I am mainly waiting for VS Code to get this functionality built-in so no-one has to get an extension for something so fundamental anymore. Here's hoping that happens soon.
